### ISSUE TITLE
Use grid instead of flexbox

### ISSUE THREAD

**Issue by itsisak** [webkom/abanav#18]
Currently we use flexbox which results in the cards at the bottom of the page not being aligned in the best way possible. (see image).

Solution: Change to css grid, so that the last cards would be placed to the left.

<img width="1386" alt="Skjermbilde 2023-03-14 kl  22 02 42" src="https://user-images.githubusercontent.com/45620425/225135623-7a72123c-19ec-4117-8baa-1626f020830b.png">

**Comment by haukkagu** [comment]
Resolved in #27
